# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/feenster/dev/geo/lastools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/feenster/dev/geo/lastools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all:
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feenster/dev/geo/lastools/CMakeFiles /home/feenster/dev/geo/lastools//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/feenster/dev/geo/lastools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

#=============================================================================
# Target rules for targets named LASlib

# Build rule for target.
LASlib:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LASlib
.PHONY : LASlib

# fast build rule for target.
LASlib/fast:
	$(MAKE) $(MAKESILENT) -f LASlib/src/CMakeFiles/LASlib.dir/build.make LASlib/src/CMakeFiles/LASlib.dir/build
.PHONY : LASlib/fast

#=============================================================================
# Target rules for targets named laszip

# Build rule for target.
laszip:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 laszip
.PHONY : laszip

# fast build rule for target.
laszip/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/laszip.dir/build.make src/CMakeFiles/laszip.dir/build
.PHONY : laszip/fast

#=============================================================================
# Target rules for targets named lasinfo

# Build rule for target.
lasinfo:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lasinfo
.PHONY : lasinfo

# fast build rule for target.
lasinfo/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/lasinfo.dir/build.make src/CMakeFiles/lasinfo.dir/build
.PHONY : lasinfo/fast

#=============================================================================
# Target rules for targets named lasindex

# Build rule for target.
lasindex:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lasindex
.PHONY : lasindex

# fast build rule for target.
lasindex/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/lasindex.dir/build.make src/CMakeFiles/lasindex.dir/build
.PHONY : lasindex/fast

#=============================================================================
# Target rules for targets named las2las

# Build rule for target.
las2las:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 las2las
.PHONY : las2las

# fast build rule for target.
las2las/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/las2las.dir/build.make src/CMakeFiles/las2las.dir/build
.PHONY : las2las/fast

#=============================================================================
# Target rules for targets named lasmerge

# Build rule for target.
lasmerge:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lasmerge
.PHONY : lasmerge

# fast build rule for target.
lasmerge/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/lasmerge.dir/build.make src/CMakeFiles/lasmerge.dir/build
.PHONY : lasmerge/fast

#=============================================================================
# Target rules for targets named txt2las

# Build rule for target.
txt2las:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 txt2las
.PHONY : txt2las

# fast build rule for target.
txt2las/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/txt2las.dir/build.make src/CMakeFiles/txt2las.dir/build
.PHONY : txt2las/fast

#=============================================================================
# Target rules for targets named las2txt

# Build rule for target.
las2txt:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 las2txt
.PHONY : las2txt

# fast build rule for target.
las2txt/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/las2txt.dir/build.make src/CMakeFiles/las2txt.dir/build
.PHONY : las2txt/fast

#=============================================================================
# Target rules for targets named lasdiff

# Build rule for target.
lasdiff:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lasdiff
.PHONY : lasdiff

# fast build rule for target.
lasdiff/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/lasdiff.dir/build.make src/CMakeFiles/lasdiff.dir/build
.PHONY : lasdiff/fast

#=============================================================================
# Target rules for targets named lasprecision

# Build rule for target.
lasprecision:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lasprecision
.PHONY : lasprecision

# fast build rule for target.
lasprecision/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/lasprecision.dir/build.make src/CMakeFiles/lasprecision.dir/build
.PHONY : lasprecision/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... LASlib"
	@echo "... las2las"
	@echo "... las2txt"
	@echo "... lasdiff"
	@echo "... lasindex"
	@echo "... lasinfo"
	@echo "... lasmerge"
	@echo "... lasprecision"
	@echo "... laszip"
	@echo "... txt2las"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

